version: '3'
networks: 
  local-net:

services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: always
    ports: 
      - 15672:15672 #RabbitMQ interface

  mongodb:
    image: mongo:3.4
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot